//TABLE SQL and MANUALS 
/*
-- =============================================
-- MANUALS FEATURE MIGRATION
-- =============================================

-- Create manuals table
CREATE TABLE public.manuals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text,
  content text NOT NULL,
  category text NOT NULL,
  media jsonb DEFAULT '[]'::jsonb,
  author_id uuid REFERENCES public.profiles(id),
  published boolean DEFAULT false,
  display_order integer DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Create manual_reads table to track who read what
CREATE TABLE public.manual_reads (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  manual_id bigint NOT NULL REFERENCES public.manuals(id) ON DELETE CASCADE,
  read_at timestamptz DEFAULT now(),
  UNIQUE(user_id, manual_id)
);

-- Create indexes for better performance
CREATE INDEX idx_manuals_category ON public.manuals(category);
CREATE INDEX idx_manuals_published ON public.manuals(published);
CREATE INDEX idx_manuals_display_order ON public.manuals(display_order);
CREATE INDEX idx_manual_reads_user_id ON public.manual_reads(user_id);
CREATE INDEX idx_manual_reads_manual_id ON public.manual_reads(manual_id);

-- Add comments
COMMENT ON TABLE public.manuals IS 'Training manuals and SOPs for franchise operations';
COMMENT ON TABLE public.manual_reads IS 'Tracks which users have read which manuals';
COMMENT ON COLUMN public.manuals.media IS 'Array of media objects: { url: string, type: "image"|"video", caption?: string }';
COMMENT ON COLUMN public.manuals.category IS 'Categories: Equipment, Cleaning, Sales, Customer Service, etc.';

-- =============================================
-- ROW LEVEL SECURITY (RLS) for Tables
-- =============================================

-- Enable RLS
ALTER TABLE public.manuals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.manual_reads ENABLE ROW LEVEL SECURITY;

-- MANUALS policies
-- Super admin can do everything
CREATE POLICY "Super admins can manage manuals"
  ON public.manuals
  FOR ALL
  USING (is_super_admin())
  WITH CHECK (is_super_admin());

-- Everyone authenticated can read published manuals
CREATE POLICY "Everyone can read published manuals"
  ON public.manuals
  FOR SELECT
  USING (published = true AND auth.role() = 'authenticated');

-- MANUAL_READS policies
-- Users can insert their own read records
CREATE POLICY "Users can mark manuals as read"
  ON public.manual_reads
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Users can view their own read records
CREATE POLICY "Users can view own read records"
  ON public.manual_reads
  FOR SELECT
  USING (auth.uid() = user_id);

-- Super admins and managers can view all read records (for tracking)
CREATE POLICY "Admins can view all read records"
  ON public.manual_reads
  FOR SELECT
  USING (is_super_admin() OR is_admin());

-- =============================================
-- STORAGE POLICIES for manual_media bucket
-- (Run AFTER creating the bucket in Dashboard)
-- =============================================

-- Public read access (everyone can view manual media)
CREATE POLICY "Public Access Manual Media"
  ON storage.objects
  FOR SELECT
  USING (bucket_id = 'manual_media');

-- Only super admins can upload manual media
CREATE POLICY "Super Admin Can Upload Manual Media"
  ON storage.objects
  FOR INSERT
  WITH CHECK (
    (bucket_id = 'manual_media') 
    AND is_super_admin()
  );

-- Only super admins can update manual media
CREATE POLICY "Super Admin Can Update Manual Media"
  ON storage.objects
  FOR UPDATE
  USING (
    (bucket_id = 'manual_media') 
    AND is_super_admin()
  );

-- Only super admins can delete manual media
CREATE POLICY "Super Admin Can Delete Manual Media"
  ON storage.objects
  FOR DELETE
  USING (
    (bucket_id = 'manual_media') 
    AND is_super_admin()
  );
*/



// ---------------------------------------------
// MANUAL CATEGORIESW
// ---------------------------------------------
export const MANUAL_CATEGORIES = {
	EQUIPMENT: 'equipment',
	CLEANING: 'cleaning',
	SALES: 'sales',
	CUSTOMER_SERVICE: 'customer_service',
	SAFETY: 'safety',
	INVENTORY: 'inventory',
	OPENING_CLOSING: 'opening_closing',
	OTHER: 'other'
} as const;

export type ManualCategory = (typeof MANUAL_CATEGORIES)[keyof typeof MANUAL_CATEGORIES];

// Category labels for UI display
export const MANUAL_CATEGORY_LABELS: Record<ManualCategory, string> = {
	equipment: 'Εξοπλισμός',
	cleaning: 'Καθαριότητα',
	sales: 'Πωλήσεις',
	customer_service: 'Εξυπηρέτηση Πελατών',
	safety: 'Ασφάλεια',
	inventory: 'Αποθήκη',
	opening_closing: 'Άνοιγμα/Κλείσιμο',
	other: 'Άλλο'
};

// ---------------------------------------------
// MEDIA TYPES
// ---------------------------------------------
export interface Manual {
	id: number;
	title: string;
	description: string | null;
	content: string;
	category: ManualCategory;
	media: string[];
	author_id: string; // UUID
	published: boolean;
	display_order: number;
	created_at: string; // ISO timestamp
	updated_at: string; // ISO timestamp
}

export interface ManualInsert {
	title: string;
	description?: string | null;
	content: string;
	category: ManualCategory;
	media?: string[];
	author_id: string;
	published?: boolean;
	display_order?: number;
}

export interface ManualUpdate {
	title?: string;
	description?: string | null;
	content?: string;
	category?: ManualCategory;
	media?: string[];
	published?: boolean;
	display_order?: number;
	updated_at?: string;
}


// MANUAL READS (Tracking)
// ---------------------------------------------
export interface ManualRead {
	id: number;
	user_id: string; // UUID
	manual_id: number;
	read_at: string; // ISO timestamp
}

export interface ManualReadInsert {
	user_id: string;
	manual_id: number;
}

// ---------------------------------------------
// JOINED / VIEW TYPES
// ---------------------------------------------

// Manual with author profile info
export interface ManualWithAuthor extends Manual {
	profiles: {
		id: string;
		username: string;
		image_url: string | null;
	} | null;
}

// Manual with read status for current user
export interface ManualWithReadStatus extends Manual {
	is_read: boolean;
	read_at: string | null;
}

// Manual with full details for display
export interface ManualWithDetails extends ManualWithAuthor {
	is_read?: boolean;
	read_at?: string | null;
	read_count?: number; // Total reads by all users
}

// For admin view - manual with read statistics
export interface ManualWithStats extends ManualWithAuthor {
	total_reads: number;
	unique_readers: number;
	last_read_at: string | null;
}

// Reader info for tracking who read the manual
export interface ManualReader {
	user_id: string;
	username: string;
	image_url: string | null;
	badge_color: string;
	read_at: string;
}

// ---------------------------------------------
// API RESPONSE TYPES
// ---------------------------------------------

export interface ManualsListResponse {
	success: boolean;
	message: string;
	manuals: ManualWithDetails[];
	categories?: ManualCategory[];
}

export interface ManualDetailResponse {
	success: boolean;
	message: string;
	manual: ManualWithDetails | null;
}

export interface ManualReadersResponse {
	success: boolean;
	message: string;
	readers: ManualReader[];
	total_count: number;
}

// ---------------------------------------------
// FILTER & SORT TYPES
// ---------------------------------------------

export interface ManualsFilter {
	category?: ManualCategory;
	published?: boolean;
	search?: string;
}

export type ManualsSortField = 'title' | 'category' | 'display_order' | 'created_at' | 'updated_at';
export type SortDirection = 'asc' | 'desc';

export interface ManualsSort {
	field: ManualsSortField;
	direction: SortDirection;
}